name: advertising_id
description: A Flutter plugin to access advertising ID.Wraps ASIdentifierManager.advertisingIdentifier (on iOS) and advertising ID (on Android).
version: 0.9.3
author: Shinobu Okano <okanoshinobu8@gmail.com>
homepage: https://github.com/operando/advertising_id
repository: https://github.com/operando/advertising_id

flutter:
  plugin:
    androidPackage: com.os.operando.advertisingid
    pluginClass: AdvertisingIdPlugin

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=1.21.0 <3.0.0"
  flutter: ">=0.1.4"